# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 13:40
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20170227_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tax_override',
            field=models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity'),
        ),
    ]
