# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20170530_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttax',
            name='scope',
        ),
    ]
