# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 22:25
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20170522_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase')], max_length=1)),
                ('tax_label', models.CharField(blank=True, max_length=128, verbose_name='Short text printed on invoices')),
                ('tax', models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(0)], verbose_name='tax %')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(0)], verbose_name='tax %'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='tax_override',
            field=models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_tax', to='product.ProductTax', verbose_name='product class'),
        ),
    ]
