# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20170522_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttax',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Tax name (optional)'),
        ),
        migrations.AlterField(
            model_name='producttax',
            name='scope',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase')], max_length=128),
        ),
    ]
