# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 10:01
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_product_wholesale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=Decimal('10'), validators=[django.core.validators.MinValueValidator(0)], verbose_name='low stock threshold'),
        ),
    ]
