# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.PriceField(currency='KES', decimal_places=2, max_digits=12, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_tax', to='product.ProductTax', verbose_name='product class'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='Wholesale price'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='price override'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='wholesale_override',
            field=django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='wholesale override'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=django_prices.models.PriceField(blank=True, currency='KES', decimal_places=2, max_digits=12, null=True, verbose_name='cost price'),
        ),
    ]
