# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_auto_20170608_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxs', to='product.ProductTax', verbose_name='product class'),
        ),
    ]
